import '@/app/globals.css'
import { Footer, Header, ThemeProvider } from '@/components'
import '@zzik-meok/ui/styles.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header>Header</Header>
            <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
              {children}
            </main>
            <Footer>Footer</Footer>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}

export default RootLayout
